#!/bin/bash

# Copyright (c) 2024-2025, University of Bern, Department for BioMedical Research, Sebastian Bruno Ulrich JORDI
# This source code is licensed under the MIT No Attribution License (MIT-0)
# found in the LICENSE file in the root directory of this source tree.

# StrainCascade_LJA_assembly.sh
# Description: Performs La Jolla Assembler (LJA) genome assembly as part of StrainCascade

set -euo pipefail

# Function to display usage information
show_usage() {
    cat << EOF
Usage: $0 <script_dir> <logs_dir> <log_name> <utils_file> <apptainer_images_dir> <input_file> 
          <output_dir> <sample_name> <sequencing_type> <threads> <genome_assembly_main_abs> <reproducibility_mode>
EOF
    exit 1
}

# Validate input parameters
[[ $# -eq 12 ]] || show_usage

# Constants from command line arguments
readonly SCRIPT_DIR="$1"
readonly LOGS_DIR="$2"
readonly LOG_NAME="$3"
readonly UTILS_FILE="$4"
readonly APPTAINER_DIR="$5"
readonly INPUT_FILE="$6"
readonly OUTPUT_DIR="$7"
readonly SAMPLE_NAME="$8"
readonly SEQUENCING_TYPE="$9"
readonly INITIAL_THREADS="${10}"
readonly GENOME_ASSEMBLY_DIR="${11}"
readonly REPRODUCIBILITY_MODE="${12}"

# Set threads based on algorithm type
if [[ "${REPRODUCIBILITY_MODE}" == "deterministic" ]]; then
    readonly THREADS=1
else
    readonly THREADS="${INITIAL_THREADS}"
fi

# Derived constants
readonly LJA_OUTPUT_DIR="$OUTPUT_DIR/LJA_assembly_results"
readonly MIN_VALID_GENOME_SIZE=1300000
readonly MAX_PLAUSIBLE_GENOME_SIZE=10000000
readonly ASSEMBLY_PREFIX="${SAMPLE_NAME}_assembly_lja"
readonly FINAL_ASSEMBLY_NAME="${ASSEMBLY_PREFIX}.fasta"

# Source utility functions
source "$UTILS_FILE"

log "$LOGS_DIR" "$LOG_NAME" "Threads set to ${THREADS} based on algorithm type ${REPRODUCIBILITY_MODE}."

# Create required output directory
create_directory "$LJA_OUTPUT_DIR"

# Clean up empty FASTA files
log "$LOGS_DIR" "$LOG_NAME" "Checking for empty FASTA files in $GENOME_ASSEMBLY_DIR"
while IFS= read -r -d '' file; do
    if [[ -f "$file" && ! -s "$file" ]]; then
        log "$LOGS_DIR" "$LOG_NAME" "Removing empty file: $(basename "$file")"
        rm "$file"
    fi
done < <(find "$GENOME_ASSEMBLY_DIR" -type f -name "*.fasta" -print0)

# Find required Apptainer image
readonly straincascade_lja_genome_assembly_sif=$(find_apptainer_sif_file "$APPTAINER_DIR" 'straincascade_lja_genome_assembly*.sif')

# Validate sequencing type
if [[ "$SEQUENCING_TYPE" != "pacbio-hifi" ]]; then
    log "$LOGS_DIR" "StrainCascade.log" "Warning: Running La Jolla Assembler for $SEQUENCING_TYPE sequencing data. \
Note: LJA was developed and optimized for high-fidelity 'pacbio-hifi' data. Results with other sequencing types may vary in quality."
fi

# Determine if genome size estimation is needed
readonly GENOME_SIZE_FILE="$GENOME_ASSEMBLY_DIR/informed_genome_size_estimation.txt"
readonly ESTIMATE_GENOME_SIZE=$([[ -f "$GENOME_SIZE_FILE" ]] && echo "no" || echo "yes")

# Create deterministic entropy source
readonly ENTROPY_FILE="$LJA_OUTPUT_DIR/deterministic_entropy_file"
if [[ ! -f "$ENTROPY_FILE" ]]; then
    dd if=/dev/zero bs=1024 count=100 > "$ENTROPY_FILE"
    log "$LOGS_DIR" "StrainCascade.log" "Deterministic entropy file created at $ENTROPY_FILE"
fi

# Run La Jolla Assembler
log "$LOGS_DIR" "StrainCascade.log" "Running La Jolla Assembler for $INPUT_FILE"
log "$LOGS_DIR" "StrainCascade.log" "Output directory: $LJA_OUTPUT_DIR"
log "$LOGS_DIR" "StrainCascade.log" "Using $THREADS threads"

apptainer exec \
    --bind "$(dirname "$INPUT_FILE")":/mnt/input \
    --bind "$LJA_OUTPUT_DIR":/mnt/output \
    --bind "$ENTROPY_FILE":/dev/random \
    --bind "$ENTROPY_FILE":/dev/urandom \
    "$straincascade_lja_genome_assembly_sif" lja \
    -o /mnt/output \
    --reads "/mnt/input/$(basename "$INPUT_FILE")" \
    --threads "$THREADS" || {
    log "$LOGS_DIR" "StrainCascade.log" "Error: La Jolla Assembler failed for $INPUT_FILE. Skipping LJA assembly."
    exit 0
}

# Process assembly output
if [[ -f "$LJA_OUTPUT_DIR/assembly.fasta" ]]; then
    # Check if file is empty
    if [[ ! -s "$LJA_OUTPUT_DIR/assembly.fasta" ]]; then
        log "$LOGS_DIR" "StrainCascade.log" "Warning: Empty assembly file was generated by LJA. This is indicative of assembly failure and the assembly file will not be used downstream."
        exit 0
    fi

    mv "$LJA_OUTPUT_DIR/assembly.fasta" "$LJA_OUTPUT_DIR/$FINAL_ASSEMBLY_NAME"
    log "$LOGS_DIR" "StrainCascade.log" "Renamed assembly.fasta to $FINAL_ASSEMBLY_NAME"
    
    cp "$LJA_OUTPUT_DIR/$FINAL_ASSEMBLY_NAME" "$GENOME_ASSEMBLY_DIR/"
    log "$LOGS_DIR" "StrainCascade.log" "Copied assembly to $GENOME_ASSEMBLY_DIR"
else
    log "$LOGS_DIR" "StrainCascade.log" "Error: Assembly file not found in $LJA_OUTPUT_DIR. Skipping LJA assembly."
    exit 0
fi

# Perform genome size estimation if needed
if [[ "$ESTIMATE_GENOME_SIZE" == "yes" ]]; then
    log "$LOGS_DIR" "StrainCascade.log" "Performing genome size estimation"
    
    # Select first assembly file for estimation
    readarray -t fasta_files < <(find "$GENOME_ASSEMBLY_DIR" -name "*.fasta")
    if [[ ${#fasta_files[@]} -eq 0 ]]; then
        log "$LOGS_DIR" "StrainCascade.log" "Error: No FASTA files found for genome size estimation. Skipping LJA assembly."
        exit 0
    fi
    selected_fasta="${fasta_files[0]}"
    
    # Calculate genome size with error handling
    if ! genome_size=$(grep -v ">" "$selected_fasta" | tr -d '\n' | tr -cd 'ACGTNacgtn' | wc -c); then
        log "$LOGS_DIR" "StrainCascade.log" "Error: Failed to calculate genome size from assembly. Skipping LJA assembly."
        exit 0
    fi
    log "$LOGS_DIR" "StrainCascade.log" "Estimated genome size: $genome_size bp"
    
    # Validate genome size
    if (( genome_size > MAX_PLAUSIBLE_GENOME_SIZE )); then
        log "$LOGS_DIR" "StrainCascade.log" "Warning: Genome size $genome_size bp is implausibly large for gut bacteria \
(https://doi.org/10.1038/s41467-023-37396-x, Fig. 1a). Skipping LJA assembly."
        exit 0
    elif (( genome_size <= MIN_VALID_GENOME_SIZE )); then
        log "$LOGS_DIR" "StrainCascade.log" "Warning: Genome size $genome_size bp may be too small for independent cell replication \
(https://www.science.org/doi/10.1126/science.1114057, Fig. 1). Skipping LJA assembly."
        exit 0
    else
        log "$LOGS_DIR" "StrainCascade.log" "Genome size $genome_size bp is within expected range"
        echo "$genome_size" > "$GENOME_SIZE_FILE"
    fi
fi

# Clean up empty FASTA files
log "$LOGS_DIR" "$LOG_NAME" "Checking for empty FASTA files in $GENOME_ASSEMBLY_DIR"
while IFS= read -r -d '' file; do
    if [[ -f "$file" && ! -s "$file" ]]; then
        log "$LOGS_DIR" "$LOG_NAME" "Removing empty file: $(basename "$file")"
        rm "$file"
    fi
done < <(find "$GENOME_ASSEMBLY_DIR" -type f -name "*.fasta" -print0)

log "$LOGS_DIR" "StrainCascade.log" "LJA assembly completed successfully"